# PyTorch


## Tensors Basics

In [1]:
import torch
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int32')

In [5]:
type(arr)

numpy.ndarray

In [6]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [7]:
x = torch.from_numpy(arr)

In [8]:
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [9]:
type(x)

torch.Tensor

In [10]:
y = torch.as_tensor(x)

In [11]:
y

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
y.dtype

torch.int32

In [15]:
arr = np.arange(0.0,12.0).reshape(4,3)

In [16]:
arr

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [17]:
x = torch.from_numpy(arr)

print(x)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


In [18]:
arr = np.arange(0.0,12.0)

In [19]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
my_tensor_copy = torch.tensor(arr)

print(my_tensor_copy)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)


In [21]:
my_tensor_deep_copy = torch.from_numpy(arr)

print(my_tensor_deep_copy)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)


In [24]:
arr[0] = 99999

arr

array([9.9999e+04, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00,
       5.0000e+00, 6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00,
       1.0000e+01, 1.1000e+01])

In [25]:
print(my_tensor_copy)

print(my_tensor_deep_copy)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)
tensor([9.9999e+04, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00,
        6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01],
       dtype=torch.float64)


**Note:-** 
- torch.from_numpy and torch.as_tensor doesn't allocate a new memory, hence, any changes to the array will reflect on tensors

- We can use torch.tensor to create a shallow copy of array so when array is overridden, it won't be reflected on our tensor 

In [26]:
my_arr = np.array([1,2,3,4,5])

tensor = torch.tensor(my_arr)

Tensor = torch.Tensor(my_arr)


print(tensor)

print(Tensor)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
tensor([1., 2., 3., 4., 5.])


**The difference between torch.tensor and torch.Tensor is that torch.tensor infers the original data type of the array while torch.Tensor infers the float version**

## Creating Tensors from scracth

In [27]:
# empty tensor with values very small
torch.empty((4,3))

tensor([[1.0653e-38, 1.0194e-38, 4.6838e-39],
        [4.2245e-39, 9.6429e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 4.2246e-39],
        [1.1112e-38, 1.4714e-43, 0.0000e+00]])

In [29]:
# dtype by default float
torch.zeros(4,5, dtype=int)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [30]:
torch.ones(4,5, dtype=int)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [31]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [33]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [35]:
torch.linspace(0, 18, 12).reshape(4,3)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [36]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [37]:
# changing data types of tensor

my_tensor = torch.tensor([1,2,3])

In [38]:
my_tensor.dtype

torch.int64

In [39]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [40]:
torch.rand(4,3)

tensor([[0.6752, 0.9222, 0.4551],
        [0.9990, 0.8970, 0.3056],
        [0.4919, 0.8982, 0.2607],
        [0.6731, 0.6482, 0.4933]])

In [41]:
torch.randn(4,3)

tensor([[-0.6604, -0.8578,  0.7432],
        [ 1.0896,  0.2451,  0.6538],
        [ 0.4715, -0.5578, -0.0717],
        [-0.2578,  0.1250,  0.9812]])

In [42]:
torch.randint(0,19,size=(5,5))

tensor([[ 4,  4, 11,  5, 17],
        [ 7,  5,  4,  3, 14],
        [11, 14, 10, 14,  7],
        [ 2, 18,  3,  1,  2],
        [12,  7, 10,  2,  4]])

In [44]:
## Generating random values of input size of existing tensor


x = torch.zeros(3,5)

x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [45]:
torch.rand_like(x)

tensor([[0.6991, 0.2740, 0.8786, 0.2935, 0.7655],
        [0.5610, 0.3483, 0.3379, 0.2505, 0.6803],
        [0.7710, 0.2427, 0.3981, 0.4907, 0.8363]])

In [46]:
torch.randn_like(x)

tensor([[ 0.2666, -1.5911, -1.5880, -0.1975, -0.6214],
        [ 0.5165,  1.1305,  0.5189,  0.0743,  0.2307],
        [ 0.4861,  0.3027,  0.0903, -1.0089, -0.3014]])

In [48]:
torch.randint_like(x, low=2, high=11)

tensor([[ 7.,  7.,  9.,  4., 10.],
        [ 6.,  8.,  8.,  2.,  7.],
        [ 4.,  9.,  2.,  7.,  9.]])

In [53]:
torch.manual_seed(42)

torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

## Operations on Tensors

In [54]:
# indexing 

x = torch.arange(6).reshape(3,2)

In [55]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [56]:
x[1,1]

tensor(3)

In [57]:
x[:, 1]

tensor([1, 3, 5])

In [58]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [59]:
x = torch.arange(10).view(5,2)

In [60]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [61]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [62]:
x = torch.arange(10)

In [63]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# infers the 2nd dimension
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Arithmetic with tensors

In [65]:
a = torch.tensor([1., 2., 3.])

b = torch.tensor([4., 5., 6.])

In [66]:
a+b

tensor([5., 7., 9.])

In [67]:
# for inplace addition

a.mul_(b)

tensor([ 4., 10., 18.])

In [68]:
a

tensor([ 4., 10., 18.])

In [69]:
# element-wise multiplication
a*b

tensor([ 16.,  50., 108.])

In [71]:
# Matrix multiplication (Dot Product)

a.dot(b)

tensor(174.)

In [72]:
torch.matmul(a, b)

tensor(174.)

In [79]:
# for higher dimensions

a = torch.arange(6).reshape(2,3)

b = torch.arange(7,13).reshape(3,2)

In [80]:
print(a)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [81]:
print(b)

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [83]:
torch.matmul(a, b)

tensor([[ 31,  34],
        [112, 124]])

In [84]:
torch.mm(a, b)

tensor([[ 31,  34],
        [112, 124]])

In [85]:
a @ b

tensor([[ 31,  34],
        [112, 124]])

In [86]:
## Euclidian norm

z = torch.tensor([1., 2., 3., 4., 5.])

In [87]:
z.norm()

tensor(7.4162)

In [88]:
x.numel()

10